[package]
name = "wyvern-vulkan"
version = "0.1.0"
authors = ["Dario Ostuni <dario.ostuni@gmail.com>"]

[dependencies]
wyvern-core = { path = "../wyvern-core" }
rspirv = "0.5"
spirv_headers = "1.3"
byteorder = "1.2"
vulkano = "0.11"
rand = "0.5.0-pre.0"
tempfile = "3"
